### PR TITLE
Loading item template

### PR DESCRIPTION
**Pull request by jseminck**
This solves feature request: https://github.com/zurb/tribute/issues/314 - Not sure if there are any side-details regarding the implementation that I should consider?

Perhaps it would be good to show the loading indicator only on the first load of remote data and not on subsequent fetches? But that should be an option to the user. In our case for example, we are fetching the data only in the beginning but then keep everything cached locally.

loading

### CODE REVIEW

**Comment by laimonas** [comment]
This is really needed functionality, can this PR be prioritized?

**Comment by jseminck** [comment]
@laimonas can you test it out, to see if it works? Otherwise, it is quite simple PR... so I hope if it satisfies the requirements that it can be merged.

**Comment by mrsweaters** [comment]
@jseminck This looks good and since it is rendered inside the menu container it should be easily styled. Can you resolve the conflicts and I'll get it merged in.

**Comment by jseminck** [comment]
@mrsweaters let's continue with this on the new PR by @cgross : https://github.com/zurb/tribute/pull/490

**Review by Bat3an — APPROVED** [review]

**Pull request closed without merging**
