### PR TITLE
Add autocompleteSeparator parameter

### PR DESCRIPTION
**Pull request by valentinstn**
The added option (`autocompleteSeparator`) allows to change the separator to allow autocompletion for other characters than spaces.

E.g., if the option is set to `new RegExp(/\-|\+|\*|\//)`, the autocomplete option opens after all of the following symbols: `-, +, *, /`, allowing an autocompletion directly after those symbols.

This is a draft PR, if I can do something to allow merging this back to upstream, please let me know!

This PR would close https://github.com/zurb/tribute/issues/393.

### CODE REVIEW

**Comment by mrsweaters** [comment]
This seems like a great idea @m55c55. Would you be interested in seeing this through? I just pushed an update to the build that removes gulp in favor of Rollup.

**Comment by m55c55** [comment]
@mrsweaters what do you mean with "seeing this through"?

**Comment by mrsweaters** [comment]
Sorry for the confusion. It looks solid, but it will need some tests to cover the changes before we can merge it in.

**Comment by m55c55** [comment]
Thanks, got it. I'll give it a try in the next weeks.

**Comment by m55c55** [comment]
I've pushed a test for this functionality. Please let me know if I can help any further.

**Comment by m55c55** [comment]
Is there anything I can do to help merging this feature?

**Comment by mrsweaters** [comment]
Can you fix the merge conflicts? This looks good, thanks for updating the test suite!

**Comment by valentinstn** [comment]
@mrsweaters Yep! I just ported the changes to the new version. This PR has no conflicts now.

**Pull request merged**
