### PR TITLE
make autocomplete work on textarea with newlines

### PR DESCRIPTION
**Pull request by Postlagerkarte**
no suggestions if tribute is used in autocomplete mode in a textarea with newlines

How to reproduce?

use tribute in textarea with autocomplete mode , hit enter after you typed a word (make sure there is no space at the end of the line), you won't get suggestions in the newline

### CODE REVIEW

**Comment by Akitsu** [comment]
When will this be merged?

**Comment by Postlagerkarte** [comment]
@mrsweaters : This is just a tiny change that is why I did not put any tests in.  Are you ok with the PR?

**Comment by mrsweaters** [comment]
@Postlagerkarte This looks good! Can you resolve the merge conflicts?

**Comment by Postlagerkarte** [comment]
@mrsweaters: resolved the conflicts.

By the way, is there a specific reason that the /dist folder is under source control? ( Would probably reduce merge conflicts if it is not )

**Pull request closed without merging**
