### PR TITLE
Add configuration to set list item class

### PR DESCRIPTION
**Pull request by mattwiller**
I'd like to be able to set a specific class on each `li` in the list of results, in order to style the list better.  This PR adds an `itemClass` configuration option which will be applied to each `li` element when the list is created in the DOM.

### CODE REVIEW

**Comment by mrsweaters** [comment]
This looks great! Can you also update the README as well with the new configuration and I'll merge it in.

**Comment by mattwiller** [comment]
@mrsweaters Of course — I just updated the README.

**Comment by mrsweaters** [comment]
Thanks!

**Comment by lcwalther** [comment]
Hey, any plans of releasing this soon? I need this on my project and do not want to fork it just to have the current master.

**Comment by mrsweaters** [comment]
@lcwalther Done! Apologies for the delay.

**Comment by lcwalther** [comment]
@mrsweaters Awesome, thanks!

**Pull request merged**
