### PR TITLE
Enable skip local search when user wants server side to execute the filtering

### PR DESCRIPTION
**Pull request by onhate**
With the addition of a new searchOpts.skip property it enables the user to skip the local filtering, this is very handy when using a server side that executes the search and filtering and in this case tribute is just the render engine for the data.

```
new Tribute({ searchOpts: { skip: true } });
```

### CODE REVIEW

**Comment by onhate** [comment]
@mrsweaters any thoughts on this subject?

**Comment by mrsweaters** [comment]
This looks great and makes total sense. Could you add a test for this functionality?

**Comment by onhate** [comment]
@mrsweaters done!

**Comment by mrsweaters** [comment]
Thanks @onhate!

**Comment by hamsterbacke23** [comment]
Thanks for implementing it, could this be added to the documentation, I looked forever for a way to do this.

**Comment by mrsweaters** [comment]
@hamsterbacke23 Good point, updated!

**Pull request merged**
