### PR TITLE
Fix IE type errors

### PR DESCRIPTION
**Pull request by first87**
I have been getting several type errors on IE 11 like these:
 - `Unable to get property 'substring' of undefined or null reference`
 - `Unable to get property 'selectionStart' of undefined or null reference`
 - `Unable to get property 'value' of undefined or null reference`

These are mainly generated from `getTextPrecedingCurrentSelection()` and I have no idea of why they happened (they didn't happen on Chrome, FF, etc). Though I have been trying to fix them, however I honestly say that my fixes didn't handle the main cause but just resolved the problems that faced my eyes.

Hope to clarify these errors and provide a stable solution.

### CODE REVIEW

**Comment by mrsweaters** [comment]
@first87 Thanks for taking a look at this issue! I'll review it and let you know.

**Comment by BorntraegerMarc** [comment]
@mrsweaters any update on your review? We also need this bug fix

**Comment by mrsweaters** [comment]
I'm not able to reproduce these errors on either master or your branch in BrowserStack. I don't have access to a windows computer. @BorntraegerMarc does this PR fix the issue for you?

**Comment by mrsweaters** [comment]
@first87 Can you update your PR with master?

**Comment by mrsweaters** [comment]
@first87 Thanks for updating! Are you still experiencing these issues? I'm not able to reproduce them?

**Comment by first87** [comment]
@mrsweaters Yes, I am. And as I already told you, I have no idea of why they happened.

**Comment by mrsweaters** [comment]
@first87 Thanks again! My apologies for asking again. I appreciate you filing this issue.

**Comment by first87** [comment]
@mrsweaters To give more info, I attach the `tribute` into the `<textarea>` field, and so the error specifically occurs when the field got or lost focus.

**Comment by mrsweaters** [comment]
@first87 I was able to reproduce the issue on an empty input, and it does appear that your fix improves upon the implementation. I'll merge this in!

**Comment by BorntraegerMarc** [comment]
@mrsweaters can you release a new version?

**Comment by mrsweaters** [comment]
@BorntraegerMarc I've got a couple of more issues I want to fix and I'll push out 3.0.1 this afternoon.

**Comment by BorntraegerMarc** [comment]
@mrsweaters cool, thx! It's already evening here, but I know whatcha mean ;)

**Comment by mrsweaters** [comment]
@BorntraegerMarc haha, well here is some dessert then. pushed! 🍰

**Pull request merged**
