### PR TITLE
Fix for scroll offset on menuContainer or window.

### PR DESCRIPTION
**Pull request by mrsweaters**
This pull request addresses the scroll offset issues discussed in https://github.com/zurb/tribute/issues/10.

### CODE REVIEW

**Comment by jmlavoier** [comment]
@mrsweaters Good, I did some tests, all right, just a detail, but i can create another issue to fix this. When i'm typing on the bottom of window, the menu is cutting, you needs to subtract the height of menu. 
screen shot 2016-07-20 at 4 08 43 pm

**Comment by mrsweaters** [comment]
@jmlavoier Are you not able to scroll further down? The scrollTo function is meant to bring the menu into view, but, since the menu height could be of arbitrary size, because it is defined the CSS, it could potentially be bigger than the height of the viewport, which means that if we subtracted the height we could eventually bring your input line out of view.

**Comment by jmlavoier** [comment]
@mrsweaters I understand it's not my case. But there will be situations where the user will not be able to scroll further down. So would you let this to another feature as an improvement?

**Comment by mrsweaters** [comment]
@jmlavoier Yeah, if you could open another issue outlining the use cases here as well. I'm not sure why a user would not be able to scroll further down. If I can wrap my head around these use cases, then I can find a solution. If you also would like to work on it, I'm more than willing to accept a pull request.

**Comment by mrsweaters** [comment]
I'm going to go ahead and merge this into master.

**Pull request merged**
