### PR TITLE
Allowing for remote data

### PR DESCRIPTION
**Pull request by renehamburger**
How about allowing for collection data to be loaded remotely through? Below is an initial version with minimal changes to the actual code (see [first commit](https://github.com/zurb/tribute/commit/27cc7c43bc583b17f9d235e7bb6e131fd15e7010?w=0)).

Here are a few remaining issues/tasks:
- keyup() is currently called twice, both by the keyup and the input event
- Remote data is currently only loaded when a character is added, but not when a character is removed
- Should the Github API by another open API without rate limit?

### CODE REVIEW

**Comment by mrsweaters** [comment]
This is a great idea. Maybe the example could use something like http://mockbin.org/ to demonstrate the functionality? I'm not sure what is causing the `keyup` and `input` events to fire twice. If you can fix up the remaining issues I'll merge it in!

**Comment by renehamburger** [comment]
Sure! I'll pick that up again when I get a chance in the next couple of weeks.

**Comment by renehamburger** [comment]
@mrsweaters, I've replaced the GitHub API by mockbin.org.

Your code calls the keyup manually, whenever the input event is triggered. But, with the exception of navigational keys, key-ups always trigger an input event anyway (at least in modern browsers). That's why showMenuFor() is called twice, too.

What is the reason for the additional input handler? Browser compatibility or capturing a paste?

I've also spotted that even in your original example with two triggers, the `@` is removed on selection but the`#` not.

**Comment by mrsweaters** [comment]
Yes, both of these events were bound to be compatible with older browsers. This was added because IE does not support the `input` event on `contenteditable` elements. It works fine for regular inputs however.

This is also an issue, or was, on some mobile devices. 

For your second point? Is that for elements that support multiple bound instances?

Thanks for your help on this!

**Comment by renehamburger** [comment]
I've added a solution to prevent superfluous calls of `showMenuFor()`. This seemed to be the safest option, safer than changing the way input and keyup events are handled.

The `@` in the contenteditables in the example was simply missing in the template. I've added that.

I spotted another small issue for the second contenteditable in the example: as it doesn't display a no-match template, whenever no matches are found, the menu is closed and removing characters with backspace doesn't bring it back as it does in the other contenteditable and the inputs.

**Comment by renehamburger** [comment]
@mrsweaters, have you had a chance to look at the final PR?

**Comment by mrsweaters** [comment]
@renehamburger I should have some time to look at this today! Thank you for reminding me.

**Comment by mrsweaters** [comment]
This looks god! Merging!

**Pull request merged**
