### PR TITLE
Emit input event

### PR DESCRIPTION
**Pull request by BrennaEpp**
As of before this commit, no input event was triggered, which meant that the value of an input field would not change until the user made another change in the input field. 

It makes sense that pressing enter or clicking to replace some text with Tribute would emit an input event that could be listened for along with other input events.

This fixes a bug when using Tribute on a `q-input` (from the [Quasar framework](https://quasar.dev/)) - if you click off the input field right after hitting enter or clicking to replace, the replacement text disappears.

### CODE REVIEW

**Comment by BrennaEpp** [comment]
@mrsweaters tagging you for visibility as you have most commits/seem to be the owner; not sure how often this repo is updated.

**Comment by mrsweaters** [comment]
This looks good. However, this does drop support for IE as `new Event` is not supported. I'm fine with this as long as you think the market is small enough. If so, let's remove IE9+ from the README.

**Comment by BrennaEpp** [comment]
> This looks good. However, this does drop support for IE as `new Event` is not supported. I'm fine with this as long as you think the market is small enough. If so, let's remove IE9+ from the README.

Oh, right. I see you're already using the polyfill for `CustomEvent`. I'll go ahead and update the pull request to use the polyfill from `src/utils` and change `new Event` to `new CustomEvent`, if you're all good with that. That should keep support for IE9+.

**Comment by mrsweaters** [comment]
Thanks! It looks good!

**Pull request merged**
