### PR TITLE
 Provide an option to allow an inline menu

### PR DESCRIPTION
**Pull request by jamescryer**
I need the menu to appear below the input in a static position.  This PR attempts to add to that capability,

### CODE REVIEW

**Comment by mrsweaters** [comment]
This inlines it in the DOM but shouldn't it be inlined relative to the position of the target element? Right now this would inline it relative to the body, which may not be what you want.

**Comment by jamescryer** [comment]
It might be what the user wants; but in my case I used the `menuContainer` option to specify where it should be inlined.

**Comment by mrsweaters** [comment]
@jamescryer Okay that is a fine approach. Could you update the readme to reflect this?

**Comment by jamescryer** [comment]
https://github.com/zurb/tribute/pull/82/commits/de786908c59f366c84c8ffabf0964cfc8d5f1acc

How can I make the README more clear?

**Comment by mrsweaters** [comment]
Ah! I didn't see the part about the menuContainer. Merging!

**Pull request merged**
